### ISSUE TITLE
Customize update timeframes

### ISSUE THREAD

**Issue by rodolphebertozzo** [audrasjb/wp-autoupdates#62]
It would be nice to be able to allow users to choose the update periods for plugins and themes, for example right away when the update is available, or some customizable deadlines (2 hours, 12 hours,...).

**Comment by pbiron** [comment]
The updates happen on the `wp_version_check` cron job (which calls [wp_version_check()](https://developer.wordpress.org/reference/functions/wp_version_check/)), which core schedules for twice a day.

Since the scheduling of **all** cron jobs can be filtered with [schedule_event](https://developer.wordpress.org/reference/hooks/schedule_event/), I would say that a feature like you're asking for is "plugin territory".  But that's just my opinion.

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/12_
