### ISSUE TITLE
Validate design for themes screen

### ISSUE THREAD

**Issue by jeffpaul** [audrasjb/wp-autoupdates#69]
We'll want to ensure the WordPress Design team reviews the themes screen work and that implementation within this plugin matches those mockups.

**Comment by bookdude13** [comment]
The latest comment from the [Trac ticket](https://core.trac.wordpress.org/ticket/49199) proposed something like the following for single themes:
<img width="1162" alt="themes_updates_section_at_bottom" src="https://user-images.githubusercontent.com/6414232/77249926-cfe9bf80-6c44-11ea-8fcc-2b04e4affe49.png">

And for multisite we can add a column/standardize to the plugins design, since the screens are so similar.

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/18_
